SELECT DISTINCT PERSONA.Activo_Retirado as retiradol,
	Grado.Grado_sapiens as nomgrado,
	RIGHT(Curso.Curso,1) as curso, 
	PERSONA.Apellido1 as apealu, 
	PERSONA.Apellido2 as segape, 
	PERSONA.Nombre1 as nomalu, 
	PERSONA.Nombre2 as segnom, 
	PERSONA.Codigo as codigo, 
	Nivel.Nivel as nivel, 
	DATE_FORMAT(PERSONA.Fecha_Nacimiento,'%d/%m/%Y') as fechanac,
	PERSONA.Lugar_Nacimiento_Municipio as lugarnaci, 
	PERSONA.Lugar_Nacimiento_Departamento as lugarnacd, 
	PERSONA.Nacionalidad as nacionali, 
	PERSONA.Direccion_Residencia as direccion, 
	PERSONA.Telefono as telefono, 
	PERSONA.Telefono2 as tele1, 
	PERSONA.Religion as religion, 
	PERSONA.Tipo_Documento as codide, 
	PERSONA.No_Documento as idealu, 
	PERSONA.Lugar_Expedicion_Municipio as identifimu, 
	PERSONA.Lugar_Expedicion_Departamento as identifide, 
	PERSONA.Barrio as barrio, 
	PERSONA.Municipio as municio, 
	PERSONA.Departamento as departa, 
	PERSONA.Salud_Prepagada as saludpre, 
	PERSONA.EPS as eps, 
	PERSONA.Numero_Contrato_Salud as numerocon, 
	PERSONA.Clinica_Emergencia as clinicaeme, 
	PERSONA.Vive_Con as vivecon, 
	PERSONA.Tipo_Sangre as tiposangre, 
	PERSONA.Sexo as sexo, 
	PERSONA.email as emailalu, 
	PERSONA.Codigo_Familia as nrofamilia, 
	PERSONA.Fecha_Ingreso as fechaing, 
	PERSONA.Curso_Ingreso as cursoant, 
	PERSONA.Fecha_Retiro as fecharet, 
	PERSONA.Colegio_Anterior as colanterio, 
	PERSONA.Hijo_de_Exalumno as eshijoex, 
	PADRE.Apellido1 as apepapa, 
	PADRE.Apellido2 as seapepa, 
	PADRE.Nombre1 as nompapa, 
	PADRE.Nombre2 as segnompa, 
	PADRE.Tipo_Documento as tipoidep, 
	PADRE.No_Documento as numerop, 
	PADRE.Lugar_Expedicion_Municipio as numicipa, 
	PADRE.Nacionalidad as nacionapa, 
	DATE_FORMAT(PADRE.Fecha_Nacimiento,'%d/%m/%Y') as fechanacpa,
	PADRE.Profesion as profpadre, 
	PADRE.Empresa as emppadre, 
	PADRE.Cargo as cargopadre, 
	PADRE.Direccion_Oficina as dirpadre, 
	PADRE.Telefono_Oficina as telpadre, 
	PADRE.Direccion_Residencia as dirrespadr, 
	PADRE.Telefono as telpadre1, 
	PADRE.Telefono2 as telcelp, 
	PADRE.email as emailpadre,
	MADRE.Apellido1 as apemama, 
	MADRE.Apellido2 as seapema, 
	MADRE.Nombre1 as nommama, 
	MADRE.Nombre2 as segnomma, 
	MADRE.Tipo_Documento as tipoidem, 
	MADRE.No_Documento numerom, 
	MADRE.Lugar_Expedicion_Municipio as municima, 
	DATE_FORMAT(MADRE.Fecha_Nacimiento,'%d/%m/%Y') as fechanacma,
	MADRE.Nacionalidad as nacionama, 
	MADRE.Profesion as profmadre, 
	MADRE.Empresa as empmadre, 
	MADRE.Cargo as cargomadre, 
	MADRE.Direccion_Oficina as dirmadre, 
	MADRE.Telefono_Oficina as telmadre, 
	MADRE.Direccion_Residencia as dirresmadr, 
	MADRE.Telefono as telmadre1, 
	MADRE.Telefono2 as telcelm, 
	MADRE.email as emailmadre,
	ACUDIENTE.Apellido1 as apeacudien, 
	ACUDIENTE.Apellido2 as segapeacud, 
	ACUDIENTE.Nombre1 as nomacudien, 
	ACUDIENTE.Nombre2 as segnomacud, 
	ACUDIENTE.Tipo_Documento as tipdocac, 
	ACUDIENTE.No_Documento as numeroacu, 
	ACUDIENTE.Lugar_Expedicion_Municipio as municiacu,
	DATE_FORMAT(ACUDIENTE.Fecha_Nacimiento,'%d/%m/%Y') as fechahacac,
	ACUDIENTE.Nacionalidad as nacionaacu,
	ACUDIENTE.email as emailacudi,
	ACUDIENTE.Profesion as profesiacu, 
	ACUDIENTE.Empresa as empreacu, 
	ACUDIENTE.Cargo as cargoacu, 
	ACUDIENTE.Telefono2 as celacudien,
	ACUDIENTE.Telefono_Oficina as teleofiacu, 
	ACUDIENTE.Direccion_Residencia as dirresacu, 
	ACUDIENTE.Telefono as teleresacu, 
	ACUDIENTE.Parentesco as parentes,
	PERSONA.Ruta_M as rutaam,
	PERSONA.Ruta_T as rutapm,
	PERSONA.Nombre_LDAP as claveing,
	PERSONA.Toma_Almuerzo as tomaalmu,
	PERSONA.Toma_Medias_Nueves as tomamedi,
	PERSONA.Toma_Seguro_Accidentes as tomasegu,
	PERSONA.No_Plaqueta as noplaque,
	tiene_responsable_MADRE(PERSONA.Grupo_Familiar_ID_Grupo_Familiar) as responma,
	tiene_responsable_PADRE(PERSONA.Grupo_Familiar_ID_Grupo_Familiar) as responpa,
	tiene_responsable_ACUDIENTE(PERSONA.Grupo_Familiar_ID_Grupo_Familiar) as responac,
	PADRE.numero_tarjeta_credito as tarjepad,
	MADRE.numero_tarjeta_credito as tarjemad,
	ACUDIENTE.numero_tarjeta_credito as tarjeacud,	
	numero_tarjeta_davivienda(MADRE.No_Documento) as tarjetanumm_matriculas,
	numero_tarjeta_davivienda(PADRE.No_Documento) as tarjetanump_matriculas,
	numero_tarjeta_davivienda(ACUDIENTE.No_Documento) as tarjetanuma_matriculas,
	0 as Estexr,
	1 as mnvo,
	0 as mproc
FROM Insc_Alum_Curso INNER JOIN PERSONA ON Insc_Alum_Curso.Persona_Id_Persona = PERSONA.Id_Persona
	INNER JOIN Curso ON Insc_Alum_Curso.Curso_Id_Curso = Curso.Id_Curso
	INNER JOIN Grado ON Curso.Grado_Id_Grado = Grado.Id_Grado
	INNER JOIN Nivel ON Grado.Nivel_Id_Nivel = Nivel.Id_Nivel
	LEFT JOIN PERSONA PADRE ON PERSONA.Grupo_Familiar_ID_Grupo_Familiar = PADRE.Grupo_Familiar_ID_Grupo_Familiar
	LEFT JOIN PERSONA MADRE ON PERSONA.Grupo_Familiar_ID_Grupo_Familiar = MADRE.Grupo_Familiar_ID_Grupo_Familiar
	LEFT JOIN PERSONA ACUDIENTE ON PERSONA.Grupo_Familiar_ID_Grupo_Familiar = ACUDIENTE.Grupo_Familiar_ID_Grupo_Familiar
WHERE 
	PERSONA.Tipo_Persona_Id_Tipo_Persona = 1 AND
	(PADRE.Tipo_Persona_Id_Tipo_Persona = 10 OR PADRE.Tipo_Persona_Id_Tipo_Persona = 2  OR PADRE.Tipo_Persona_Id_Tipo_Persona = 4   OR PADRE.Tipo_Persona_Id_Tipo_Persona = 6  OR PADRE.Tipo_Persona_Id_Tipo_Persona = 7 OR  PADRE.Tipo_Persona_Id_Tipo_Persona = 8)  AND
	(MADRE.Tipo_Persona_Id_Tipo_Persona = 12 OR MADRE.Tipo_Persona_Id_Tipo_Persona = 4  OR MADRE.Tipo_Persona_Id_Tipo_Persona = 6  OR MADRE.Tipo_Persona_Id_Tipo_Persona = 7  OR MADRE.Tipo_Persona_Id_Tipo_Persona = 8 OR MADRE.Tipo_Persona_Id_Tipo_Persona = 10) AND
	(ACUDIENTE.Tipo_Persona_Id_Tipo_Persona = 3 OR ACUDIENTE.Tipo_Persona_Id_Tipo_Persona = 4 OR ACUDIENTE.Tipo_Persona_Id_Tipo_Persona = 10  OR ACUDIENTE.Tipo_Persona_Id_Tipo_Persona = 6 OR ACUDIENTE.Tipo_Persona_Id_Tipo_Persona = 7  OR ACUDIENTE.Tipo_Persona_Id_Tipo_Persona = 8) AND
	Insc_Alum_Curso.SY_Id_SY = 5 
AND Insc_Alum_Curso.Curso_Id_Curso >= 10101 and curso.Id_Curso <= 40403
and PERSONA.Activo_Retirado = 1
and PERSONA.matriculado = 1
GROUP BY PERSONA.Id_Persona