SELECT DISTINCT PERSONA.Activo_Retirado as retiradol,
	Grado.Grado_sapiens as nomgrado,
	RIGHT(Curso.Curso,1) as curso, 
	PERSONA.Apellido1 as apealu, 
	PERSONA.Apellido2 as segape, 
	PERSONA.Nombre1 as nomalu, 
	PERSONA.Nombre2 as segnom, 
	PERSONA.Codigo as codigo, 
	Nivel.Nivel as nivel, 
	DATE_FORMAT(PERSONA.Fecha_Nacimiento,'%d/%m/%Y') as fechanac,
	PERSONA.Lugar_Nacimiento_Municipio as lugarnaci, 
	PERSONA.Lugar_Nacimiento_Departamento as lugarnacd, 
	PERSONA.Nacionalidad as nacionali, 
	PERSONA.Direccion_Residencia as direccion, 
	PERSONA.Telefono as telefono, 
	PERSONA.Telefono2 as tele1, 
	PERSONA.Religion as religion, 
	PERSONA.Tipo_Documento as codide, 
	PERSONA.No_Documento as idealu, 
	PERSONA.Lugar_Expedicion_Municipio as identifimu, 
	PERSONA.Lugar_Expedicion_Departamento as identifide, 
	PERSONA.Barrio as barrio, 
	PERSONA.Municipio as municio, 
	PERSONA.Departamento as departa, 
	PERSONA.Salud_Prepagada as saludpre, 
	PERSONA.EPS as eps, 
	PERSONA.Numero_Contrato_Salud as numerocon, 
	PERSONA.Clinica_Emergencia as clinicaeme, 
	PERSONA.Vive_Con as vivecon, 
	PERSONA.Tipo_Sangre as tiposangre, 
	PERSONA.Sexo as sexo, 
	PERSONA.email as emailalu, 
	PERSONA.Codigo_Familia as nrofamilia, 
	PERSONA.Fecha_Ingreso as fechaing, 
	PERSONA.Curso_Ingreso as cursoant, 
	PERSONA.Fecha_Retiro as fecharet, 
	PERSONA.Colegio_Anterior as colanterio, 
	PERSONA.Hijo_de_Exalumno as eshijoex, 
	"" as apemama, 
	"" as seapema, 
	"" as nommama, 
	"" as segnomma, 
	"" as tipoidem, 
	"" as numerom, 
	"" as municima, 
	"" as fechanacma,
	"" as nacionama, 
	"" as profmadre, 
	"" as empmadre, 
	"" as cargomadre, 
	"" as dirmadre, 
	"" as telmadre, 
	"" as dirresmadr, 
	"" as telmadre1, 
	"" as telcelm, 
	"" as emailmadre,
	"" as apeacudien, 
	"" as segapeacud, 
	"" as nomacudien, 
	"" as segnomacud, 
	"" as tipdocac, 
	"" as numeroacu, 
	"" as municiacu,
	"" as fechahacac,
	"" as nacionaacu,
	"" as emailacudi,
	"" as profesiacu, 
	"" as empreacu, 
	"" as cargoacu, 
	"" as celacudien,
	"" teleofiacu, 
	"" as dirresacu, 
	"" as teleresacu, 
	"" as parentes,
PADRE.Apellido1 as apeacudien, 
	PADRE.Apellido2 as segapeacud, 
	PADRE.Nombre1 as nomacudien, 
	PADRE.Nombre2 as segnomacud, 
	PADRE.Tipo_Documento as tipdocac, 
	PADRE.No_Documento as numeroacu, 
	PADRE.Lugar_Expedicion_Municipio as municiacu,
	DATE_FORMAT(PADRE.Fecha_Nacimiento,'%d/%m/%Y') as fechahacac,
	PADRE.Nacionalidad as nacionaacu,
	PADRE.email as emailacudi,
	PADRE.Profesion as profesiacu, 
	PADRE.Empresa as empreacu, 
	PADRE.Cargo as cargoacu, 
	PADRE.Telefono2 as celacudien,
	PADRE.Telefono_Oficina as teleofiacu, 
	PADRE.Direccion_Residencia as dirresacu, 
	PADRE.Telefono as teleresacu, 
	PADRE.Parentesco as parentes,
	PERSONA.Ruta_M as rutaam,
	PERSONA.Ruta_T as rutapm,
	PERSONA.Nombre_LDAP as claveing,
	PERSONA.Toma_Almuerzo as tomaalmu,
	PERSONA.Toma_Medias_Nueves as tomamedi,
	PERSONA.Toma_Seguro_Accidentes as tomasegu,
	PERSONA.No_Plaqueta as noplaque,
	0 as responma,
	tiene_responsable_PADRE(PERSONA.Grupo_Familiar_ID_Grupo_Familiar) as responpa,
	0 as responac,
	"" as tarjetanum,
	numero_tarjeta_davivienda(PADRE.No_Documento) as tarjetanum,
	"" as tarjetanum,
	0 as Estexr,
	1 as mnvo,
	0 as mproc
FROM Insc_Alum_Curso INNER JOIN PERSONA ON Insc_Alum_Curso.Persona_Id_Persona = PERSONA.Id_Persona
	INNER JOIN Curso ON Insc_Alum_Curso.Curso_Id_Curso = Curso.Id_Curso
	INNER JOIN Grado ON Curso.Grado_Id_Grado = Grado.Id_Grado
	INNER JOIN Nivel ON Grado.Nivel_Id_Nivel = Nivel.Id_Nivel
	LEFT OUTER JOIN PERSONA PADRE ON PERSONA.Grupo_Familiar_ID_Grupo_Familiar = PADRE.Grupo_Familiar_ID_Grupo_Familiar
WHERE 
   /*PERSONA.Activo_Retirado = 1 and*/
	PERSONA.Tipo_Persona_Id_Tipo_Persona = 1 AND
	(PADRE.Tipo_Persona_Id_Tipo_Persona = 2 OR PADRE.Tipo_Persona_Id_Tipo_Persona = 4 OR PADRE.Tipo_Persona_Id_Tipo_Persona = 10 OR PADRE.Tipo_Persona_Id_Tipo_Persona = 6 OR PADRE.Tipo_Persona_Id_Tipo_Persona = 7 OR PADRE.Tipo_Persona_Id_Tipo_Persona = 8 OR PADRE.Tipo_Persona_Id_Tipo_Persona = 12 OR PADRE.Tipo_Persona_Id_Tipo_Persona = 14) AND
	/*PADRE.Sexo = "MASCULINO" AND */
	/*MADRE.Sexo = "FEMENINO" AND */
	Insc_Alum_Curso.SY_Id_SY = 4 AND
	EXISTS (select * from PERSONA padre where (padre.Tipo_Persona_Id_Tipo_Persona = 3 or padre.Tipo_Persona_Id_Tipo_Persona = 12 OR padre.Tipo_Persona_Id_Tipo_Persona = 7 OR padre.Tipo_Persona_Id_Tipo_Persona = 4 OR padre.Tipo_Persona_Id_Tipo_Persona = 6 OR padre.Tipo_Persona_Id_Tipo_Persona = 8 OR padre.Tipo_Persona_Id_Tipo_Persona = 10 OR padre.Tipo_Persona_Id_Tipo_Persona = 14) and padre.Grupo_Familiar_Id_Grupo_Familiar = PERSONA.Grupo_Familiar_ID_Grupo_Familiar) = false
/*AND curso.Grado_Id_Grado = 101 and */
AND Insc_Alum_Curso.Curso_Id_Curso >= 10101 and curso.Id_Curso <= 40403
and PERSONA.Activo_Retirado = 1
and PERSONA.matriculado = 1
GROUP BY PERSONA.Id_Persona